swiftmailer:
    transport: gmail
    username: '%env(MAILER_USERNAME)%'
    password: '%env(MAILER_PASSWORD)%'
    host: localhost
    port: 465
    encryption: ssl
    auth_mode: login
    spool: { type: 'memory' }
    stream_options:
        allow_self_signed: true
        verify_peer: false
        verify_peer_name: false